### ISSUE TITLE
Customer does not keep authenticated when navigating from Catalyst storefront to Optimized One-Page Checkout

### ISSUE THREAD

**Issue by Pedro-Silva-MM** [bigcommerce/catalyst#1059]
**Describe the bug**
Running a Catalyst application locally, logging in as a customer, adding items to the cart and proceeding to checkout even though the user was authenticated on the storefront the checkout prompts the user to log in.

**To Reproduce**
1. Run a Catalyst application locally
2. Log in as a customer
3. Add items to the cart
4. Go to checkout

**Expected behavior**
The customer should remain authenticated from storefront to checkout.

<img width="1264" alt="image" src="https://github.com/bigcommerce/catalyst/assets/172405652/c82a16fc-aab3-4762-802a-584eb9342563">
<img width="1514" alt="image" src="https://github.com/bigcommerce/catalyst/assets/172405652/77db6833-163e-498a-9346-86c1d58b005e">

**Comment by bookernath** [comment]
Thanks for your report @Pedro-Silva-MM. This is being added very soon with an improvement to the GraphQL Storefront API which will persist the customer session through to the checkout.

In the meantime, if you require this functionality right now, you can look at the approach in this PR which uses the Customer Login API to do so: https://github.com/bigcommerce/catalyst/pull/715

This approach requires a Client Secret from an API account created directly in the BigCommerce Control Panel.

Once we release our new approach, this will become a feature of the GraphQL Storefront API and will not require any additional credentials.

I'll keep this issue open until we release our new feature.

**Comment by Pedro-Silva-MM** [comment]
Thank you =)

**Comment by smotlythomas** [comment]
We have the same issue, some updates about this ?

**Comment by jorgemoya** [comment]
#1262 should fix this issue but we're finalizing some details before we merge.

**Comment by jorgeserras** [comment]
> #1262 should fix this issue but we're finalizing some details before we merge.

Any expected date for the merge?

**Comment by chanceaclark** [comment]
We have been delayed after testing some fixes for this functionality in our other environments. Still waiting on security review to release this further. Thanks for bearing with us on this!

**Comment by chanceaclark** [comment]
This should fixed in a Catalyst -> Checkout direction. We still need to implement some stuff, both in Catalyst and in checkout to support keeping logged in state in the other direction but I think we can consider this fixed for now.

**Comment by guido-ferraro** [comment]
> support keeping logged in state in the other direction

Was this fixed? I'm encountering this issue at the moment.
