### ISSUE TITLE
Feedback for “The Catalyst monorepo”

### ISSUE THREAD

**Issue by willPrattUPL** [bigcommerce/catalyst#1096]
![image](https://github.com/user-attachments/assets/4418737f-e70e-47a9-b84f-ae8f166d16ea)
Links not functional

- The [core Next.js reference storefront application, in /apps/core](https://github.com/bigcommerce/catalyst/tree/main/apps/core)
- [The component library, in /packages/components](https://github.com/bigcommerce/catalyst/tree/main/packages/components)
- [A Storybook instance to help explore the component library in /apps/docs](https://github.com/bigcommerce/catalyst/tree/main/apps/docs)
- [Functional tests in Playwright, in /packages/functional](https://github.com/bigcommerce/catalyst/tree/main/packages/functional)

**Comment by chanceaclark** [comment]
Hey @willPrattUPL, seems like you might have an older version of the documentation locally. The current version should be here: https://github.com/bigcommerce/catalyst/blob/main/docs/monorepo.md

I went through that documentation and checked the links, looks like the only broken one was the `/package/components` link which I created a PR to update: https://github.com/bigcommerce/catalyst/pull/1097

Thanks for pointing this out!
