### ISSUE TITLE
Failed to clone Catalyst template

### ISSUE THREAD

**Issue by myphotoir** [bigcommerce/catalyst#1265]
When running "npm create @bigcommerce/catalyst@latest" after I select the channel it fails to clone the template

Using node 20.11.1

✖ Failed to clone Catalyst template: Failed to download https://api.github.com/repos/bigcommerce/catalyst/tarball/@bigcommerce/catalyst-core@0.13.0: 404 Not Found

**Comment by matthewvolk** [comment]
Hi @myphotoir! Thanks for the report - we're working on a fix for this now 👍 Will update here once resolved

**Comment by chanceaclark** [comment]
Should be fixed now. Let us know if you run into it again 🙏
