### ISSUE TITLE
Product redirects when Base64 id ends in "=" never resolve their redirect (Broken page)

### ISSUE THREAD

**Issue by willPrattUPL** [bigcommerce/catalyst#1320]
**Describe the bug**
Certain product redirects do an infinite redirect loop / never resolve.  This means the page never loads.

It seems to only occur if the base64 id ends in an "=". I have tested many configurations of dynamic links/product pages/not product pages/manual links. The commonalities are:

- Product page
- Manual links
- Base64 ends in "="

**To Reproduce**
1. Create manual redirect in BC control panel
2. Update or force route.node.id to end in "=" (?)
3. Go to "new url" link locally (not old url)
4. Go to with-routes and observe the switch case logic
```ts
    if (route?.redirect) {
      switch (route.redirect.to.__typename) {

        case 'ManualRedirect': {
          // For manual redirects, redirect to the full URL to handle cases
          // where the destination URL might be external to the site
          return NextResponse.redirect(route.redirect.toUrl, redirectConfig);
        }

        default: {
          // For all other cases, assume an internal redirect and construct the URL
          // based on the current request URL to maintain internal redirection
          // in non-production environments
          const redirectPathname = new URL(route.redirect.toUrl).pathname;
          const redirectUrl = new URL(redirectPathname, request.url);

          return NextResponse.redirect(redirectUrl, redirectConfig);
        }
      }
    }
```

**Expected behavior**
Page should load normally with 0 redirects

**Comment by bookernath** [comment]
Thanks for the report! We'll take a look.

**Comment by willPrattUPL** [comment]
@bookernath Thanks Nathan

We haven't looked into this in awhile, but looking back at it I think the route.node.id was a red herring


I think the issue might be that it's logically always taking the redirect without checking that route.node exists and is valid.

 Is this off base?

**Comment by chanceaclark** [comment]
Fixed in #1429 & #1459

**Comment by willPrattUPL** [comment]
Requesting this re-opened

https://github.com/bigcommerce/catalyst/pull/1459#issuecomment-2422439402

**Comment by chanceaclark** [comment]
Keeping it closed for now: https://github.com/bigcommerce/catalyst/pull/1459#issuecomment-2422637877
