### ISSUE TITLE
Docs refer to order history and management but this is not implemented

### ISSUE THREAD

**Issue by styler3** [bigcommerce/catalyst#1515]
Hi :wave:

In the overview in the docs:

> Order information for logged-in customers. This includes order history, order status, order details, tracking information, and tracking info and shipment addresses for each consignment

https://github.com/bigcommerce/catalyst/blob/691ec2bcbb8839446463e292856080cc9b16c584/docs/index.md?plain=1#L26

however it seems this functionality doesn't exist OOTB; in `core/app/[locale]/(default)/account/(tabs)/layout.tsx` there is:

```
const tabList = ['addresses', 'settings'] as const;
```

Is this a planned feature that is not implemented yet, or does it exist somewhere in the code-base that I've missed?

If it is not implemented yet, maybe the docs need to be updated to make this clear?

**Comment by chanceaclark** [comment]
Hey @styler3, thanks for pointing this out!

We actually are in the process of implementing it right now. You can check out the branch here: https://github.com/bigcommerce/catalyst/tree/account-orders

We are missing a few pieces for customer order management, from an API standpoint, and are trying to determine what we can release as-is right now. If you wanted to, you can cherry-pick or copy and paste the code from that branch if you need that functionality now. However, we are _hoping_ to get it released soon.

**Comment by styler3** [comment]
Thanks @chanceaclark Looking forward to this feature!

Would you consider removing it from the docs' feature list until it's officially released?

When scoping work for clients, having the feature there can cause a bit of confusion.

**Comment by chanceaclark** [comment]
Hey @styler3,

That sounds like a good idea for now. We can revert the documentation removal as soon as we release the feature.

Thanks for providing this feedback!
