### ISSUE TITLE
https dev server is not working with NextJS flag --experimental-https 

### ISSUE THREAD

**Issue by oliverdowie** [bigcommerce/catalyst#1691]
**Describe the bug**
When trying to run the development server locally with `--experimental-https`, the CLI will not progress past this point:
`Attempting to generate self signed certificate. This may prompt for your password`

**To Reproduce**
1. Change dev script in `core/package.json` to `"dev": "npm run generate && next dev --turbo --experimental-https`
2. Run `pnpm run dev`
3. Observe

**Expected behavior**
Should be prompted to enter system password, or certificate should be generated.

**Additional context**
Catalyst core version: 0.21.0

**Comment by chanceaclark** [comment]
Hey @oliverdowie, I was able to get this working on the latest version of Catalyst:
![Screenshot 2024-12-02 at 10 39 41](https://github.com/user-attachments/assets/cfe145a8-c5c1-476e-96c7-88a58dad8f07)

Have you tried reproducing this with a normal create-next-app to see if you can reproduce it outside of Catalyst? It also may be dependent on your node version et. al. What versions of node, pnpm, and npm are you using here?

**Comment by oliverdowie** [comment]
Thanks @chanceaclark. Looks like it's a limitation with our SOE. Going to set it up with a traefik proxy instead.

**Comment by oliverdowie** [comment]
Closing as it's not an issue with Catalyst.
