### ISSUE TITLE
suggestion for cache tags

### ISSUE THREAD

**Issue by nowlena** [bigcommerce/catalyst#849]
Not an issue but a recommendation so that there are no "magic" strings.

Can we move to using a const for all cache tags?

This will allow for autocompletion and consistency when setting cache tags and when using `revalidateTag()` to purge them.

```ts
// define our tags
export const TAGS = {
  cart: 'cart',
  checkout: 'checkout',
} as const;

// use anytime we set a cache tag
const response = await client.fetch({
  document: GET_CART_QUERY,
  fetchOptions: {
    next: {
      tags: [TAGS.cart],
    },
  },
});

// use anytime we purge via a tag
revalidateTag(TAGS.cart);
```

Thanks all, appreciate all the work and effort here!

**Comment by deini** [comment]
Completed by https://github.com/bigcommerce/catalyst/pull/850
